### ISSUE TITLE
iOS: Use `iproxy` instead of having the user specify an IP address for SSH

### ISSUE THREAD

**Issue by baltpeter** [tweaselORG/appstraction#43]
For iOS, the user currently has to specify the device's IP when instantiating the platform API object. That is already quite annoying.

It will get even more annoying with #1. For the other things, we'll likely need the UDID instead of the IP. And requiring two device IDs really isn't great.

We could avoid this problem if we used `iproxy` forward the SSH port to the host (see: https://kb.froglogic.com/squish/ios/howto/ios-automation-usb-cable-connection/ or https://iphonedev.wiki/index.php/SSH_Over_USB).

And we're already depending on libimobiledevice anyway.

**Comment by baltpeter** [comment]
> And we're already depending on libimobiledevice anyway.

Though, on Ubuntu this is split across multiple packages. To get `iproxy`, I had to install `libusbmuxd-tools`.

**Comment by baltpeter** [comment]
While working on this, I noticed another bug: #53

**Comment by zner0L** [comment]
Since the `root` user doesn’t have a password set at the intial setup, and I don’t want to expect our users to log in via `mobile` and set a password for `root`, we need some way to escalate a `mobile` login session to a more priviledged one. There are three options I can think of:
 - Set a root password ourselves and log in a root again
 - Use sudo and add `mobile` to a permissive `/etc/sudoers`
 - Use sudo and pipe the password to it and then run all commands with `sudo /bin/zsh -c`, making it symmetric to the `su -c` on Android.

I think I prefer the last option, but what do you think, @baltpeter?
